name: Generate FigureYa Contents

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout FigureYa repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate contents HTML
        run: |
          pip install beautifulsoup4
          python .github/scripts/generate_book.py

      - name: Checkout FigureYa-Contents repo
        uses: actions/checkout@v4
        with:
          repository: ying-ge/FigureYa-Contents
          path: FigureYa-Contents
          token: ${{ secrets.FIGUREYA_CONTENTS_TOKEN }}

      - name: Copy generated HTML
        run: |
          cp FigureYa_contents.html FigureYa-Contents/FigureYa_contents.html

      - name: Commit and push to FigureYa-Contents
        run: |
          cd FigureYa-Contents
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add FigureYa_contents.html
          git commit -m "Auto-update: FigureYa contents generated"
          git push