name: Build Quarto Book

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ebook repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install beautifulsoup4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Generate Quarto book sources
        run: python .github/scripts/generate_quarto_book.py

      - name: Build book
        run: |
          cd quarto_book
          quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./quarto_book/_book
          publish_branch: gh-pages
