name: Build and Sync Quarto Book to ebook repo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (FigureYa)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install beautifulsoup4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Generate Quarto book sources
        run: python .github/scripts/generate_quarto_book.py

      - name: Copy index.md to book dir (if exists)
        run: |
          if [ -f index.md ]; then cp index.md quarto_book/index.md; fi
          if [ -f index.qmd ]; then cp index.qmd quarto_book/index.qmd; fi

      - name: Show book dir contents (debug)
        run: ls -lh quarto_book

      - name: Build Quarto book
        run: |
          cd quarto_book
          quarto render

      - name: Push to FigureYa-ebook gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./quarto_book/_book
          external_repository: ying-ge/FigureYa-ebook
          publish_branch: gh-pages
          github_token: ${{ secrets.FIGUREYA_CONTENTS_TOKEN }}
