name: Classify HTML Files

on:
  workflow_dispatch: # 手动触发

jobs:
  classify:
    runs-on: ubuntu-latest
    steps:
      # Step 1: 检出代码仓库
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # 确保使用 Python 3.9

      # Step 3: 安装必要的依赖
      - name: Install dependencies
        run: pip install pyyaml requests

      # Step 4: 扫描并分类 HTML 文件
      - name: Classify HTML files
        id: classify
        run: |
          python <<EOF
          import os
          import yaml

          # 定义分类规则（根据文件内容中的关键字）
          categories = {
              "领域A": ["关键词1", "关键词2"],
              "领域B": ["关键词3", "关键词4"],
              "领域C": ["关键词5", "关键词6"],
          }

          # 扫描 HTML 文件
          results = {}
          for root, _, files in os.walk("docs"):  # 假设 HTML 文件在 docs 文件夹中
              for file in files:
                  if file.endswith(".html"):
                      filepath = os.path.join(root, file)
                      with open(filepath, "r", encoding="utf-8") as f:
                          content = f.read()
                          # 根据分类规则匹配
                          for category, keywords in categories.items():
                              if any(keyword in content for keyword in keywords):
                                  if category not in results:
                                      results[category] = []
                                  results[category].append(filepath)
                                  break

          # 输出分类结果
          with open("classification_results.yml", "w", encoding="utf-8") as f:
              yaml.dump(results, f, allow_unicode=True)

          print("分类完成，结果保存到 classification_results.yml")
          EOF

      # Step 5: 将分类结果写入 Wiki
      - name: Publish to Wiki
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # 当前目录下的分类结果会发布到 Wiki
          destination_dir: wiki
          commit_message: "更新分类结果"

      # Step 6: 清理临时文件（可选）
      - name: Clean up
        run: rm -rf classification_results.yml
