name: Compress All Folders

on:
  push:
    paths:
      - '**'
  workflow_dispatch:

jobs:
  compress-all-folders:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create compressed folder if not exists
        run: mkdir -p compressed

      - name: Zip all top-level folders
        run: |
          for dir in */ ; do
            foldername=$(basename "$dir")
            # 跳过 .git 和 compressed 本身
            if [ "$foldername" = "compressed" ] || [ "$foldername" = ".git" ]; then
              continue
            fi
            if [ -d "$dir" ]; then
              zipfile="compressed/${foldername}.zip"
              echo "Compressing $dir -> $zipfile"
              rm -f "$zipfile"
              zip -r -q "$zipfile" "$foldername"
            fi
          done

      - name: Show compressed files
        run: ls -lh compressed

      - name: Commit and push zip files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add compressed/*.zip || true
          git commit -m "Auto-compress all folders [skip ci]" || echo "Nothing to commit"
          git push || echo "Nothing to push"
