name: Mirror Repository to FigureYa-Book

on:
  # 1. 每次推送到源仓库（FigureYa）时触发
  #push:
  #  branches:
  #    - main
  
  # 2. 每天定时运行一次，作为兜底
  schedule:
    - cron: '0 12 * * *' # 每天国际标准时间 12:00 运行

  # 3. 允许手动触发
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the repository
        uses: Yikun/hub-mirror-action@v1.5 # 使用一个稳定且广泛使用的 Action
        with:
          # 源仓库，默认为当前仓库，所以这里是 'ying-ge/FigureYa'
          src: 'github/ying-ge'
          
          # 目标仓库
          dst: 'github/ying-ge'
          
          # 目标仓库的 Personal Access Token
          # 请确保这个 Secret 存在于 FigureYa 仓库的 "Settings > Secrets and variables > Actions" 中
          dst_token: ${{ secrets.FIGUREYA2ACTION }}
          
          # 要同步的仓库列表，这里我们只指定 FigureYa
          # 注意：这里的 'FigureYa' 后面不能加 '/'
          static_list: 'FigureYa'
          
          # 目标仓库的名称映射
          # 将源仓库 'FigureYa' 映射到目标仓库 'FigureYa-Book'
          mappings: 'FigureYa => FigureYa-Book'
          
          # 强制更新，会覆盖目标仓库的历史
          force_update: true
          
          # 开启后，会执行 git gc，减小仓库体积
          clone_style: "mirror"
