name: Sync All FigureYa Folders to Book Repo

on:
  schedule:
    - cron: '0 12 * * *' # 每天国际标准时间 12:00 运行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Repo (FigureYa-Book)
        uses: actions/checkout@v4
        with:
          repository: ying-ge/FigureYa-Book
          path: target-repo
          token: ${{ secrets.FIGUREYA2ACTION }}

      - name: Get last synced SHA from target repo
        id: get_last_sha
        run: |
          if [ -f target-repo/.last_synced_sha ]; then
            echo "last_sha=$(cat target-repo/.last_synced_sha)" >> $GITHUB_OUTPUT
            echo "Found last synced SHA: $(cat target-repo/.last_synced_sha)"
          else
            echo "last_sha=''" >> $GITHUB_OUTPUT
            echo "'.last_synced_sha' not found. This must be the first run."
          fi

      - name: Checkout Source Repo (FigureYa)
        uses: actions/checkout@v4
        with:
          repository: ying-ge/FigureYa
          path: source-repo
          fetch-depth: 0 # 获取所有历史记录以便 diff

      - name: Get current SHA of source repo
        id: get_current_sha
        working-directory: ./source-repo
        run: echo "current_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Determine Changed Folders
        id: changed_folders
        run: |
          cd source-repo
          LAST_SHA="${{ steps.get_last_sha.outputs.last_sha }}"
          
          # 如果 LAST_SHA 为空 (首次运行)，则同步所有 FigureYa* 文件夹
          if [ -z "$LAST_SHA" ]; then
            echo "First run. Syncing all FigureYa* folders."
            find . -maxdepth 1 -type d -name 'FigureYa*' -printf '%f\n' > ../changed_folders.txt
          else
            echo "Incremental update. Finding changes between $LAST_SHA and HEAD."
            # 找出在两次 SHA 之间有变动的 FigureYa* 文件夹
            git diff --name-only "$LAST_SHA" HEAD | grep '^FigureYa' | cut -d/ -f1 | sort -u > ../changed_folders.txt
          fi

          if [ -s ../changed_folders.txt ]; then
            echo "changed_needed=1" >> $GITHUB_OUTPUT
            echo "The following folders have changed and will be synced:"
            cat ../changed_folders.txt
          else
            echo "changed_needed=0" >> $GITHUB_OUTPUT
            echo "No changed FigureYa* folders detected."
          fi

      - name: Sync Folders if Needed
        if: steps.changed_folders.outputs.changed_needed == '1'
        run: |
          while read folder; do
            if [ -d "source-repo/$folder" ]; then
              echo "Syncing folder: $folder"
              # 先删除目标文件夹，再完整复制，防止旧文件残留
              rm -rf "target-repo/$folder"
              cp -r "source-repo/$folder" "target-repo/"
            else
              echo "Warning: Source folder '$folder' not found, skipping."
            fi
          done < changed_folders.txt

      - name: Update last_synced_sha file and Commit
        if: steps.changed_folders.outputs.changed_needed == '1'
        run: |
          cd target-repo
          # 更新 .last_synced_sha 文件
          echo "${{ steps.get_current_sha.outputs.current_sha }}" > .last_synced_sha
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Scheduled sync from FigureYa repo"
            git push
          fi
