name: Sync Included Folders to Actions Repo

on:
  push:
    paths:
      - all_included.txt
      - '**/all_included.txt'
      - '**'  # 监听所有文件变动
  workflow_dispatch:

jobs:
  sync-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          repository: ying-ge/FigureYa
          path: source-repo

      - name: Checkout Target Repo
        uses: actions/checkout@v4
        with:
          repository: ying-ge/FigureYa-Actions
          path: target-repo
          token: ${{ secrets.FIGUREYA2ACTION }}

      - name: Determine Changed Folders
        id: changed
        run: |
          cd source-repo
          git fetch origin main
          # 获取本次提交前后的所有更改文件夹
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          # 提取所有_included.txt引用的文件夹名
          cat all_included.txt | grep -v '^\s*$' | grep -v '^#' > folder_list.txt
          # 判断是否有需要同步的文件夹发生变化
          changed_needed=0
          while read folder; do
            if grep -q "^$folder/" changed_files.txt; then
              echo "$folder 发生变化"
              changed_needed=1
            fi
          done < folder_list.txt
          # 检查all_included.txt是否发生变动
          if grep -q "^all_included.txt$" changed_files.txt; then
            changed_needed=1
          fi
          echo "changed_needed=$changed_needed" >> $GITHUB_OUTPUT

      - name: Sync Folders if Needed
        if: steps.changed.outputs.changed_needed == '1'
        run: |
          cd source-repo
          while read folder; do
            if [ -d "$folder" ]; then
              echo "Copying $folder"
              rm -rf ../target-repo/"$folder"
              cp -r "$folder" ../target-repo/
            else
              echo "Warning: $folder not found"
            fi
          done < all_included.txt

      - name: Commit and Push to Target Repo
        if: steps.changed.outputs.changed_needed == '1'
        run: |
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync folders from FigureYa via workflow" || echo "No changes to commit"
          git push
