name: Format Rmd Files (Remove Extra Blank Lines)

on:
  workflow_dispatch:

jobs:
  format-rmd-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: 1. Check out repository (without LFS)
        uses: actions/checkout@v4
        # By default, lfs is false, which is exactly what we need to avoid the LFS issue.

      - name: 2. Find and Format all Rmd files
        run: |
          echo "Searching for .Rmd files and removing extra blank lines..."
          # This command finds all .Rmd files and executes a Perl one-liner on them.
          # The Perl script (-0pe 's/\n{3,}/\n\n/g') reads the whole file at once
          # and replaces any sequence of 3 or more newlines with exactly 2 newlines.
          # This effectively reduces multiple blank lines down to a single blank line.
          find . -type f -name "*.Rmd" -exec perl -i -0pe 's/\n{3,}/\n\n/g' {} +
          echo "Formatting complete."

      - name: 3. Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Check if there are any changes to commit
          if ! git diff --staged --quiet && ! git diff --quiet; then
            echo "Changes detected. Committing and pushing..."
            git add .
            git commit -m "style: Remove extra blank lines from Rmd files"
            git push
          else
            echo "No changes detected. Nothing to commit."
          fi
