# 工作流名称
name: Knit all Rmd Files

# 触发条件：可以手动触发
on:
  workflow_dispatch:

jobs:
  test-render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: 1. Check out repository
        uses: actions/checkout@v4

      - name: 2. Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgfortran5 liblapack-dev libblas-dev

      - name: 3. Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          # 将 R 版本更新到最新稳定版
          r-version: 'latest'
      
      - name: 4. Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: 5. Install core R dependencies
        run: Rscript -e 'install.packages(c("rmarkdown", "knitr"))'

      - name: 6. Find and Render the first 3 Rmd files
        run: |
          echo "RMD Render Summary (First 3 Files)" > summary.txt
          echo "======================================" >> summary.txt
          echo "" >> summary.txt

          find . -type f -name "*.Rmd" | while read rmd_file; do
            echo "--- Processing: $rmd_file ---"
            
            if Rscript -e "rmarkdown::render('$rmd_file')"; then
              echo "[SUCCESS] - $rmd_file" >> ../summary.txt
            else
              echo "[FAILED] - $rmd_file" >> ../summary.txt
            fi
            echo "--- Finished: $rmd_file ---"
            echo ""
          done

      - name: 7. Upload Render Summary
        uses: actions/upload-artifact@v4
        with:
          name: render-summary-report-first-3
          path: summary.txt

      - name: 8. Commit and Push Rendered Files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "docs: Auto-render Rmd output files by GitHub Actions"
            git push
          else
            echo "No changes to commit."
          fi
