name: Mirror Repository to FigureYa-Book

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *' # 每天国际标准时间 12:00 运行
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1: 使用 --mirror 选项克隆源仓库的所有内容
      - name: Clone source repository
        run: git clone --mirror https://github.com/ying-ge/FigureYa.git

      # 步骤 2: 使用 --mirror 选项将所有内容推送到目标仓库
      - name: Push to target repository
        run: |
          cd FigureYa.git
          git push --mirror https://x-access-token:${{ secrets.FIGUREYA2ACTION }}@github.com/ying-ge/FigureYa-Book.git
