name: Mirror Repository to FigureYa-Book

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *' # 每天国际标准时间 12:00 运行
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1: 克隆源仓库
      - name: Clone source repository
        run: git clone --mirror https://github.com/ying-ge/FigureYa.git

      # 新增步骤: 优化 Git 配置以适应大仓库推送
      - name: Configure Git for large repository push
        run: |
          git config --global http.postBuffer 524288000
          git config --global http.lowSpeedLimit 0
          git config --global http.lowSpeedTime 999999
      
      # 步骤 2: 推送到目标仓库
      - name: Push to target repository
        run: |
          cd FigureYa.git
          git push --mirror https://x-access-token:${{ secrets.FIGUREYA2ACTION }}@github.com/ying-ge/FigureYa-Book.git
