name: Daily Sync All Content to Book Repo

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 0:00 (UTC) 定时触发
  workflow_dispatch: # 保留手动触发

permissions:
  contents: write

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo (FigureYa)
        uses: actions/checkout@v4
        with:
          path: source-repo

      - name: Checkout Target Repo (FigureYa-Book)
        uses: actions/checkout@v4
        with:
          repository: ying-ge/FigureYa-Book
          path: target-repo
          token: ${{ secrets.FIGUREYA2ACTION }}

      - name: Sync files using rsync
        id: rsync
        run: |
          # rsync 会自动处理首次运行和增量更新。
          # 首次运行时，目标目录为空，它会复制所有文件。
          # 后续运行时，它会比较两个目录，只同步有差异的文件（新增、修改、删除）。
          # -a: 归档模式，保留文件属性。
          # -v: 显示详细过程。
          # --delete: 删除目标仓库中多余的文件，确保与源仓库完全一致。
          # --exclude='.git': 在同步时排除 .git 目录本身。
          rsync -av --delete --exclude='.git/' source-repo/ target-repo/

      - name: Commit and Push to Target Repo
        run: |
          cd target-repo
          
          # 检查是否有文件变动。如果没有变动，则不进行提交。
          # git status --porcelain 会在有变动时输出内容，无变动时为空。
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes detected. Nothing to commit."
            exit 0
          fi
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Daily sync from FigureYa repo"
          git push
