name: Mirror Repository to FigureYa-Book (via SSH)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *' # 每天国际标准时间 12:00 运行
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1: 使用 HTTPS 克隆源仓库 (克隆是读取操作，通常很稳定)
      - name: Clone source repository
        run: git clone --mirror https://github.com/ying-ge/FigureYa.git

      # 步骤 2: 设置 SSH 环境
      # 这个 Action 会将你的私钥加载到 SSH Agent 中，为后续的 git 命令做准备
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      # 步骤 3: 使用 SSH 协议推送到目标仓库
      - name: Push to target repository via SSH
        run: |
          cd FigureYa.git
          git remote set-url --push origin git@github.com:ying-ge/FigureYa-Book.git
          git push --mirror origin
