name: Daily Sync All Content (Skipping LFS and Pointers)

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 0:00 (UTC) 定时触发
  workflow_dispatch: # 保留手动触发

permissions:
  contents: write

jobs:
  sync-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo (FigureYa)
        uses: actions/checkout@v4
        with:
          path: source-repo

      - name: Generate LFS file list
        id: lfs_files
        run: |
          cd source-repo
          if [ -f .gitattributes ]; then
            git lfs ls-files -n > ../lfs_files_list.txt
          else
            touch ../lfs_files_list.txt
          fi
          echo "list_path=lfs_files_list.txt" >> $GITHUB_OUTPUT

      - name: Initialize and prepare Target Repo directory
        run: |
          # 核心修改1：不再检出目标仓库，而是手动创建一个
          git clone --depth=1 "https://x-access-token:${{ secrets.FIGUREYA2ACTION }}@github.com/ying-ge/FigureYa-backup.git" target-repo || \
          (mkdir target-repo && cd target-repo && git init -b main && git remote add origin "https://x-access-token:${{ secrets.FIGUREYA2ACTION }}@github.com/ying-ge/FigureYa-backup.git")
          
          # 清空目录，为 rsync 做准备
          cd target-repo
          git rm -rf . || true
          rm -rf * .[^.]* || true
          cd ..

      - name: Sync files using rsync
        run: |
          rsync -av --exclude='.git/' source-repo/ target-repo/

      - name: Remove LFS pointer files from target repo
        run: |
          cd target-repo
          if [ -s ../${{ steps.lfs_files.outputs.list_path }} ]; then
            xargs -a ../${{ steps.lfs_files.outputs.list_path }} rm -f
          fi

      - name: Commit and Push to Target Repo
        run: |
          cd target-repo
          
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes detected. Nothing to commit."
            exit 0
          fi
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Daily sync from FigureYa repo (LFS files and pointers excluded)"
          git push -u origin main --force
